FROM ckan/ckan-base:2.9.5-dev


# Set up environment variables
ENV APP_DIR=/srv/app
ENV TZ=UTC
RUN echo ${TZ} > /etc/timezone

# Make sure both files are not exactly the same
RUN if ! [ /usr/share/zoneinfo/${TZ} -ef /etc/localtime ]; then \
        cp /usr/share/zoneinfo/${TZ} /etc/localtime ;\
    fi ;

# Install CKAN
COPY /entrypoints/*.sh /docker-entrypoint.d
COPY /config $CONFIG_DIR